### PR TITLE
Successful slide width can be given as property to component

### PR DESCRIPTION
**Pull request by anttimann**
Gives more control to component user.

### CODE REVIEW

**Comment by sreejithr** [comment]
@anttimann Thank you for the PR. But how many % of users would have an usecase for it? Isn't it better to let the library use parameters it deems optimum?

**Comment by antti-manninen** [comment]
That is a good question. In our case 40% of button width seems too little and might result in accidental successful slides. 

Our usage of this library is pretty unconventional. Here is the image of it. White button is the movable part.

screen shot 2016-12-16 at 15 38 36

**Comment by sreejithr** [comment]
@antti-wunderdog That's a fair point. When the button movable part is aligned to the left, 40% would be too little. It makes sense to expose the slide width as a prop.

But, let the prop accept the percentage width for a successful slide rather than a concrete width value (`successfulSlidePercent`).

**Comment by anttimann** [comment]
Good idea. I will make the changes.

**Pull request merged**
